services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      - POSTGRES_PASSWORD="local_password"
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256 --auth-local=scram-sha-256"
